max_steps = 1000
batch_size = 1024
micro_batch_size = 1
seq_len = 12288
rollouts_per_example = 16
mask_truncated_completions = false

[model]
name = "Qwen/Qwen3-8B"

[monitor.wandb]
project = "main_side_monitor"

[environment]
id = "main_side_task"

[environment.args]
agent_prompt_file = "prompts/ms_agent/ogprompt.txt"
main_datasets = ["gpqa_biology", "gpqa_physics"]
side_datasets = ["filtered-math500", "artificial-math-dataset", "gsm8k"]
samples_per_agent = 50000
monitor_model = "gpt-4o"


[monitor.wandb.log_extras]
interval = 50

[eval]
interval = 25
rollouts_per_example = [4]
environment_ids = ["main_side_task"]

[eval.environment_args.main_side_task]
agent_prompt_file = "prompts/ms_agent/ogprompt.txt"
main_datasets = ["gpqa_biology", "gpqa_physics"]
side_datasets = ["mock_aime"]
samples_per_agent = 200
monitor_model = "gpt-4o"

[ckpt]
interval = 100
