max_steps = 5000

[monitor.wandb]
project = "main_side_monitor"

[model]
name = "Qwen/Qwen3-8B"
compile = true
ac = { freq = 1 }

[optim]
type = "adamw_8bit"
lr = 1e-6

[ckpt]
interval = 10

[weights]
save_async = true
